# Generated by Django 5.0.7 on 2024-07-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text='Gender is required', max_length=100)),
                ('married', models.BooleanField()),
                ('dependents', models.CharField(help_text='Number of dependents', max_length=10)),
                ('education', models.CharField(choices=[('graduate', 'Graduate'), ('not graduate', 'Not Graduate')], help_text='Education is required', max_length=50)),
                ('self_employed', models.BooleanField(default=False)),
                ('applicant_income', models.FloatField(help_text='Enter your income amount e.g., 25000 per month')),
                ('co_applicant_income', models.FloatField(help_text="Enter your partner's income amount e.g., 20000 per month")),
                ('loan_amount', models.FloatField(help_text='Enter your loan amount e.g., 1000000')),
                ('loan_amount_term', models.FloatField(help_text='Enter the term of the loan in months e.g., 360')),
                ('credit_history', models.BooleanField(default=True)),
                ('property_area', models.CharField(choices=[('urban', 'Urban'), ('semiurban', 'Semiurban'), ('rural', 'Rural')], max_length=255)),
                ('loan_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(null=True)),
            ],
        ),
    ]
