# Generated by Django 5.0.7 on 2024-07-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanprediction',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
