# Generated by Django 5.0.7 on 2024-07-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanprediction_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanprediction',
            name='created',
        ),
        migrations.RemoveField(
            model_name='loanprediction',
            name='updated',
        ),
    ]
