# Generated by Django 5.0.7 on 2024-07-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_remove_loanprediction_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='balance_income',
            field=models.FloatField(blank=True, default=0.0, help_text='Enter your loan amount e.g., 1000000', null=True),
        ),
        migrations.AddField(
            model_name='loanprediction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loanprediction',
            name='emi',
            field=models.FloatField(blank=True, default=0.0, help_text='Enter your loan amount e.g., 1000000', null=True),
        ),
        migrations.AddField(
            model_name='loanprediction',
            name='total_income',
            field=models.FloatField(blank=True, default=0.0, help_text='Enter your loan amount e.g., 1000000', null=True),
        ),
        migrations.AddField(
            model_name='loanprediction',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
